### ISSUE TITLE
Datatypes

### ISSUE THREAD

**Issue by MoRadwan74** [cartologic/cartoview_categorized_styler#1]
![categorized style 1](https://user-images.githubusercontent.com/30727109/29002084-b154eae8-7a9a-11e7-8956-4b0fe51d1e9e.jpg)

As we know that "Categorized Styler" is used only for String attributes, I selected a layer that we want to use in our map and it was integer and the warning is showed only when i try to select an attribute for the layer.
We can make a pop-up message to show to the user that he chooses a not-valid layer or develop an algorithm that eliminates the not-valid layers from being choosed.

< Also for English >
We can write a sentence like "String attributes only are available for this step" instead of the existing sentences.

**Comment by hishamkaram** [comment]
fixed
