### ISSUE TITLE
handle  null values

### ISSUE THREAD

**Issue by ahmednosman** [cartologic/cartoview_categorized_styler#25]
when attributes has null values, the attribute is not displayed
add a special entry to select style for null values
http://play.cartoview.net/layers/geonode:los_angeles_number_of_injuries_per_zip_2009
sum attributes has null valyes

**Comment by ahmednosman** [comment]
once null values are defined make sure the sld is still available in default geonode style editor

**Comment by hishamkaram** [comment]
fixed
