### ISSUE TITLE
issue when try to add label from default geonode styler

### ISSUE THREAD

**Issue by ahmednosman** [cartologic/cartoview_categorized_styler#28]
create a style with categorized styled
go to the layer default page
edit the style from the default geonode styler
enable the label
you will get an error popup trying to save the style
"there was an error saving the style back to the server"

**Comment by hishamkaram** [comment]
Issue moved to [cartologic/cartoview #133](https://github.com/cartologic/cartoview/issues/133) via [**ZenHub**](https://www.zenhub.com/)
